import Foundation

/// Interface labels only. The shared rules supply all game names and descriptions.
enum NativeInterfaceCopy {
    static func text(_ key: String, language: String) -> String {
        (strings[language] ?? strings["fr"]!)[key] ?? strings["en"]?[key] ?? key
    }

    private static let strings: [String: [String: String]] = [
        "fr": [
            "empire": "Mon empire", "workshops": "Ateliers", "orders": "Dossiers", "career": "Carrière",
            "settings": "Réglages", "done": "Terminer", "cancel": "Annuler", "close": "Fermer",
            "documents": "Documents", "production": "Production", "confidence": "Confiance", "culture": "Culture",
            "print": "Imprimer", "firstPrint": "Tout commence par une feuille.",
            "firstHint": "Imprime tes premiers documents pour installer ton premier atelier.",
            "build": "Installer une unité", "owned": "Unités installées", "cost": "Coût de la prochaine unité",
            "gain": "Gain de production", "nextTier": "Prochain agrandissement", "tier": "Palier",
            "details": "Voir l’atelier", "locked": "À débloquer", "notEnough": "Encore un peu de production…",
            "map": "Voir sur la carte", "zoomIn": "Agrandir la carte", "zoomOut": "Réduire la carte", "recenter": "Recentrer",
            "quality": "Qualité", "footprint": "Empreinte papier", "brand": "Image de marque",
            "upgrades": "Améliorations", "purchase": "Acheter", "purchased": "Installée",
            "plans": "Plans", "challenges": "Défis", "campaigns": "Grands dossiers", "achievements": "Succès",
            "choose": "Choisir ce plan", "abandon": "Abandonner le plan", "accept": "Accepter", "decline": "Refuser",
            "open": "Ouvrir", "completed": "Validé", "active": "En cours", "available": "Disponible",
            "contracts": "Contrats", "sign": "Signer le contrat", "refresh": "Renouveler les offres", "requirements": "Conditions",
            "reward": "Récompense", "duration": "Durée", "seconds": "s", "incident": "Incident", "resolve": "Traiter l’incident",
            "journal": "Journal", "emptyOrders": "Les premières commandes arrivent bientôt.",
            "emptyOrdersHint": "Développe ton atelier : les contrats s’ouvrent après 1 500 documents produits.",
            "prestige": "Réorganiser l’empire", "prestigeHint": "Un nouveau cycle, avec les avantages de ta carrière.",
            "confirmAction": "Confirmer cette action ?", "confirm": "Confirmer", "continue": "Continuer",
            "language": "Langue", "save": "Ta sauvegarde", "export": "Exporter ma partie", "import": "Importer une partie",
            "recover": "Récupérer la copie précédente", "importPreview": "Aperçu de la sauvegarde", "replace": "Remplacer ma partie",
            "replaceHint": "La partie actuelle sera conservée comme copie précédente. Vérifie ce fichier avant de continuer.",
            "reset": "Nouvelle partie", "resetHint": "Recommencer efface la progression active. Exporte ta partie pour la conserver.",
            "localHint": "Ta partie est enregistrée sur cet appareil. Un fichier exporté permet de continuer sur le site ou un autre appareil.",
            "share": "Partager mon empire", "offline": "Pendant ton absence", "offlineHint": "La production a continué selon les règles de ton atelier.",
            "loading": "Ouverture de ton empire…", "retry": "Réessayer", "unavailable": "L’empire n’a pas pu s’ouvrir",
            "saveError": "La sauvegarde demande ton attention", "support": "Guide de l’atelier", "appearance": "Accessibilité",
            "systemSettings": "L’app suit les réglages iOS de taille du texte, de mouvement et de transparence.",
            "controls": "Commandes de la carte", "units": "unités", "growthHint": "L’atelier s’agrandit visuellement aux paliers 10 et 25.",
            "noAchievements": "Tes premiers succès apparaîtront ici.", "earned": "Obtenu", "next": "Prochaine étape"
        ],
        "en": [
            "empire": "My empire", "workshops": "Workshops", "orders": "Orders", "career": "Career",
            "settings": "Settings", "done": "Done", "cancel": "Cancel", "close": "Close",
            "documents": "Documents", "production": "Production", "confidence": "Confidence", "culture": "Culture",
            "print": "Print", "firstPrint": "It starts with a single sheet.", "firstHint": "Print your first documents to install your first workshop.",
            "build": "Install one unit", "owned": "Installed units", "cost": "Next unit cost", "gain": "Production gain",
            "nextTier": "Next expansion", "tier": "Tier", "details": "View workshop", "locked": "Not unlocked yet",
            "notEnough": "A little more production…", "map": "Show on map", "zoomIn": "Zoom in", "zoomOut": "Zoom out", "recenter": "Recenter",
            "quality": "Quality", "footprint": "Paper footprint", "brand": "Brand image", "upgrades": "Upgrades",
            "purchase": "Buy", "purchased": "Installed", "plans": "Plans", "challenges": "Challenges", "campaigns": "Major orders",
            "achievements": "Achievements", "choose": "Choose this plan", "abandon": "Abandon plan", "accept": "Accept", "decline": "Decline",
            "open": "Open", "completed": "Completed", "active": "In progress", "available": "Available", "contracts": "Contracts",
            "sign": "Sign contract", "refresh": "Refresh offers", "requirements": "Requirements", "reward": "Reward", "duration": "Duration",
            "seconds": "s", "incident": "Incident", "resolve": "Handle incident", "journal": "Journal",
            "emptyOrders": "Your first orders are on their way.", "emptyOrdersHint": "Grow your workshop: contracts unlock after producing 1,500 documents.",
            "prestige": "Reorganize empire", "prestigeHint": "A new cycle, with the benefits of your career.",
            "confirmAction": "Confirm this action?", "confirm": "Confirm", "continue": "Continue", "language": "Language",
            "save": "Your save", "export": "Export my game", "import": "Import a game", "recover": "Recover previous copy",
            "importPreview": "Save preview", "replace": "Replace my game", "replaceHint": "Your current game will be kept as the previous copy. Check this file before continuing.",
            "reset": "New game", "resetHint": "Starting again clears active progress. Export your game to keep it.",
            "localHint": "Your game is saved on this device. An exported file lets you continue on the website or another device.",
            "share": "Share my empire", "offline": "While you were away", "offlineHint": "Production continued according to your workshop’s rules.",
            "loading": "Opening your empire…", "retry": "Try again", "unavailable": "Your empire couldn’t open",
            "saveError": "Your save needs attention", "support": "Workshop guide", "appearance": "Accessibility",
            "systemSettings": "The app follows iOS settings for text size, motion, and transparency.",
            "controls": "Map controls", "units": "units", "growthHint": "Your workshop grows visually at the 10 and 25 unit milestones.",
            "noAchievements": "Your first achievements will appear here.", "earned": "Earned", "next": "Next step"
        ],
        "de": [
            "empire": "Mein Imperium", "workshops": "Werkstätten", "orders": "Aufträge", "career": "Karriere",
            "settings": "Einstellungen", "done": "Fertig", "cancel": "Abbrechen", "close": "Schließen",
            "documents": "Dokumente", "production": "Produktion", "confidence": "Vertrauen", "culture": "Kultur",
            "print": "Drucken", "firstPrint": "Alles beginnt mit einem Blatt.", "firstHint": "Drucke erste Dokumente, um deine erste Werkstatt einzurichten.",
            "build": "Eine Einheit installieren", "owned": "Installierte Einheiten", "cost": "Kosten der nächsten Einheit", "gain": "Produktionsgewinn",
            "nextTier": "Nächster Ausbau", "tier": "Stufe", "details": "Werkstatt ansehen", "locked": "Noch gesperrt",
            "notEnough": "Noch etwas produzieren…", "map": "Auf der Karte zeigen", "zoomIn": "Vergrößern", "zoomOut": "Verkleinern", "recenter": "Zentrieren",
            "quality": "Qualität", "footprint": "Papierverbrauch", "brand": "Markenimage", "upgrades": "Verbesserungen",
            "purchase": "Kaufen", "purchased": "Installiert", "plans": "Pläne", "challenges": "Herausforderungen", "campaigns": "Großaufträge",
            "achievements": "Erfolge", "choose": "Diesen Plan wählen", "abandon": "Plan aufgeben", "accept": "Annehmen", "decline": "Ablehnen",
            "open": "Öffnen", "completed": "Abgeschlossen", "active": "In Arbeit", "available": "Verfügbar", "contracts": "Verträge",
            "sign": "Vertrag unterzeichnen", "refresh": "Angebote erneuern", "requirements": "Voraussetzungen", "reward": "Belohnung", "duration": "Dauer",
            "seconds": "s", "incident": "Vorfall", "resolve": "Vorfall bearbeiten", "journal": "Journal",
            "emptyOrders": "Die ersten Aufträge kommen bald.", "emptyOrdersHint": "Baue deine Werkstatt aus: Verträge werden nach 1.500 produzierten Dokumenten freigeschaltet.",
            "prestige": "Imperium reorganisieren", "prestigeHint": "Ein neuer Zyklus mit den Vorteilen deiner Karriere.",
            "confirmAction": "Diese Aktion bestätigen?", "confirm": "Bestätigen", "continue": "Weiter", "language": "Sprache",
            "save": "Dein Spielstand", "export": "Spielstand exportieren", "import": "Spielstand importieren", "recover": "Vorherige Kopie wiederherstellen",
            "importPreview": "Spielstandvorschau", "replace": "Meinen Spielstand ersetzen", "replaceHint": "Dein aktueller Spielstand bleibt als vorherige Kopie erhalten. Prüfe diese Datei vor dem Fortfahren.",
            "reset": "Neues Spiel", "resetHint": "Ein Neustart löscht den aktiven Fortschritt. Exportiere deinen Spielstand, um ihn zu behalten.",
            "localHint": "Dein Spiel wird auf diesem Gerät gespeichert. Mit einer exportierten Datei kannst du auf der Website oder einem anderen Gerät weiterspielen.",
            "share": "Mein Imperium teilen", "offline": "Während deiner Abwesenheit", "offlineHint": "Die Produktion lief nach den Regeln deiner Werkstatt weiter.",
            "loading": "Dein Imperium wird geöffnet…", "retry": "Erneut versuchen", "unavailable": "Dein Imperium konnte nicht geöffnet werden",
            "saveError": "Dein Spielstand braucht Aufmerksamkeit", "support": "Werkstatthandbuch", "appearance": "Bedienungshilfen",
            "systemSettings": "Die App folgt den iOS-Einstellungen für Textgröße, Bewegung und Transparenz.",
            "controls": "Kartensteuerung", "units": "Einheiten", "growthHint": "Deine Werkstatt wächst sichtbar bei 10 und 25 Einheiten.",
            "noAchievements": "Deine ersten Erfolge erscheinen hier.", "earned": "Erhalten", "next": "Nächster Schritt"
        ],
        "lb": [
            "empire": "Mäin Imperium", "workshops": "Atelieren", "orders": "Opdräg", "career": "Karriär",
            "settings": "Astellungen", "done": "Fäerdeg", "cancel": "Ofbriechen", "close": "Zoumaachen",
            "documents": "Dokumenter", "production": "Produktioun", "confidence": "Vertrauen", "culture": "Kultur",
            "print": "Drécken", "firstPrint": "Alles fänkt mat engem Blat un.", "firstHint": "Dréck deng éischt Dokumenter, fir däin éischten Atelier opzebauen.",
            "build": "Eng Eenheet installéieren", "owned": "Installéiert Eenheeten", "cost": "Käschte vun der nächster Eenheet", "gain": "Produktiounsgewënn",
            "nextTier": "Nächsten Ausbau", "tier": "Stuf", "details": "Atelier kucken", "locked": "Nach gespaart",
            "notEnough": "Nach e bësse produzéieren…", "map": "Op der Kaart weisen", "zoomIn": "Vergréisseren", "zoomOut": "Verklengeren", "recenter": "Zentréieren",
            "quality": "Qualitéit", "footprint": "Pabeierverbrauch", "brand": "Markenimage", "upgrades": "Verbesserungen",
            "purchase": "Kafen", "purchased": "Installéiert", "plans": "Pläng", "challenges": "Erausfuerderungen", "campaigns": "Grouss Opdräg",
            "achievements": "Erfolleger", "choose": "Dëse Plang wielen", "abandon": "Plang opginn", "accept": "Unhuelen", "decline": "Ofleenen",
            "open": "Opmaachen", "completed": "Ofgeschloss", "active": "Aarbecht amgaang", "available": "Disponibel", "contracts": "Kontrakter",
            "sign": "Kontrakt ënnerschreiwen", "refresh": "Offeren erneieren", "requirements": "Konditiounen", "reward": "Belounung", "duration": "Dauer",
            "seconds": "s", "incident": "Tëschefall", "resolve": "Tëschefall behandelen", "journal": "Journal",
            "emptyOrders": "Déi éischt Opdräg komme geschwënn.", "emptyOrdersHint": "Bau däin Atelier aus: Kontrakter ginn no 1.500 produzéierten Dokumenter fräigeschalt.",
            "prestige": "Imperium reorganiséieren", "prestigeHint": "En neien Zyklus mat de Virdeeler vun denger Karriär.",
            "confirmAction": "Dës Aktioun bestätegen?", "confirm": "Bestätegen", "continue": "Weider", "language": "Sprooch",
            "save": "Däi Spillstand", "export": "Spillstand exportéieren", "import": "Spillstand importéieren", "recover": "Vireg Kopie restauréieren",
            "importPreview": "Virschau vum Spillstand", "replace": "Mäi Spillstand ersetzen", "replaceHint": "Däin aktuelle Spillstand bleift als vireg Kopie erhalen. Kontrolléier dës Datei, éier s de weiderfiers.",
            "reset": "Neit Spill", "resetHint": "En Neistart läscht den aktive Fortschrëtt. Exportéier däi Spillstand, fir en ze behalen.",
            "localHint": "Däi Spill gëtt op dësem Apparat gespäichert. Mat enger exportéierter Datei kanns de op der Websäit oder engem aneren Apparat weiderspillen.",
            "share": "Mäin Imperium deelen", "offline": "Wärend denger Absence", "offlineHint": "D’Produktioun ass no de Reegelen vun dengem Atelier weidergelaf.",
            "loading": "Däin Imperium gëtt opgemaach…", "retry": "Nach eng Kéier", "unavailable": "Däin Imperium konnt net opgemaach ginn",
            "saveError": "Däi Spillstand brauch Opmierksamkeet", "support": "Atelier-Handbuch", "appearance": "Accessibilitéit",
            "systemSettings": "D’App follegt den iOS-Astellunge fir Textgréisst, Beweegung an Transparenz.",
            "controls": "Kaartesteierung", "units": "Eenheeten", "growthHint": "Däin Atelier wiisst siichtbar bei 10 a 25 Eenheeten.",
            "noAchievements": "Deng éischt Erfolleger erschéngen hei.", "earned": "Kritt", "next": "Nächste Schrëtt"
        ]
    ]
}
